version: "3.7"

services:
  database:
    image: postgres
    container_name: database_sorahius_nest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=hostdb
      - POSTGRES_DB=sorahiusdb
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local